### ISSUE TITLE
[OPS] Approaches to repeating commands problem

### ISSUE THREAD

**Issue by johnnykfeng** [Aggregate-Intellect/sherpa#172]
### PROBLEM
Look at issue #18 for original context. 
For certain questions, the agent runs a repetitive loop that uses the same command for all 5 steps. This problem causes redundancy and wasted token usage. 

### SOLUTION
1. Modify the Reflection module in `src\sherpa_ai\reflection.py`, specifically the instructions under `evaluate_actions` method.

- **Pros:** This module is already in place, surely some clever prompt engineering will fix it...
- **Cons:** Use even more tokens by doing extra LLM calls. Unpredictable response from LLMs, especially when you pass large context sizes.

2. Hard code an if condition that forces the agent to finish thoughts once it repeats the action once or twice.

- **Pros:** Very elegant solution, predictable.
- **Cons:** This may result in lower quality answers to questions by not allowing the agent to query Search or Context Search again. It's arguable whether the extra queries are necessary to improve final answers.

3. Replace the ReAct agent and build a simple chain that uses each tool to answer the question. This may have to wait for the context search tool to be fixed in issue #154 

**OUTCOME**
No more repeating commands. 
Conserve tokens --> save $$$

**Comment by amirfz** [comment]
@johnnykfeng I have been thinking about this, and I think we need more time to figure out the right setup to solve this issue and with the big refactoring going on it might be best to wait until that's done and see if the issue persists. in the meantime, since one goal is to save $$ my suggestion is to change the default QA agent for the slack app to RAG (currently ReAct). In other words, the agent would only take one of the 5 steps and then provides a response. later we will add another ReAct agent that is properly tested and calibrated in addition to this one. 

what do you think?

also curious to hear @20001LastOrder 's thoughts

**Comment by johnnykfeng** [comment]
> @johnnykfeng I have been thinking about this, and I think we need more time to figure out the right setup to solve this issue and with the big refactoring going on it might be best to wait until that's done and see if the issue persists. in the meantime, since one goal is to save $$ my suggestion is to change the default QA agent for the slack app to RAG (currently ReAct). In other words, the agent would only take one of the 5 steps and then provides a response. later we will add another ReAct agent that is properly tested and calibrated in addition to this one.
> 
> what do you think?
> 
> also curious to hear @20001LastOrder 's thoughts

Sure, my feeling is that using ReAct is a bit overkill when we're only using two tools, and both are just information based. Just using a chain that uses RAG and SerperAPI is good enough. Then it wouldn't need to go through 5 steps of prompting to answer a question, at most it takes 2 steps.

**Comment by amirfz** [comment]
that's fair. I think we still need to choose between context search and
serper, but agreed with the sentiment. I think there's also an issue to
break up the context search into a proper "context search" and specific
documentations. so we will have a few tools, but your point still holds. do
you want to modify this issue to reflect this, since there's another issue
for the repeated action already?

**Comment by 20001LastOrder** [comment]
Closed as it evolves into https://github.com/Aggregate-Intellect/sherpa/issues/237
