### ISSUE TITLE
choose the right license for this project

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#32]

**Comment by oshoma** [comment]
Right now the [license](https://github.com/Aggregate-Intellect/practical-llms/blob/main/LICENSE) is Creative Commons CC 1.0 Universal. This may be suitable for the documentation ("book") content within this repository, but not the software ("apps"). 

From the [Creative Commons website](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software):
> Can I apply a Creative Commons license to software?
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering [licenses listed as free](https://www.gnu.org/licenses/license-list#SoftwareLicenses) by the [Free Software Foundation](http://www.fsf.org/) and [listed as “open source”](http://opensource.org/licenses) by the [Open Source Initiative](http://www.opensource.org/).

Github also offers [guidance on choosing a license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#disclaimer) and, for open source licensing, points readers to https://choosealicense.com/. 

@amirfz what objectives or use cases do you have in mind that the current license does not satisfy? That would be a good starting point.

**Comment by oshoma** [comment]
My 2 cents:

1. Use a multiple-licensing structure, with one license for the software and a second license for everything else.  See, for example, [Github product docs repo](https://github.com/github/docs/tree/c6212051672ef5af5b65c15322dce93bca1ef0e8) (search for "License"). The licenses apply to specific repo folders.
2. Use CC or [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) for the non-software portions of the repo (the book). I prefer CC-BY-SA, since it gives credit to contributors (presenters, authors, etc.), spreads community awareness of the source repo, and requires people to continue using the license you chose.
3. If you want all the software contributions to be freely usable without limitation by anyone, including by Aggregate Intellect for commercial purposes, the MIT License is a decent option. There are also [other similar licenses](https://choosealicense.com/licenses/) which are broadly used.  This approach  would make good sense if Aggregate views its software contributions as "non-sensitive", i.e. not your secret sauce or a significant competitive moat.
4. If you want to open source certain components of Aggregate Intellect's commercial product and restrict others from using those software contributions to compete commercially with Aggregate Intellect, you'll need a different software license for those contributions. For example this is what Elastic is trying to achieve with their [Elastic License v2](https://www.elastic.co/blog/elastic-license-v2), along with protecting their trademarks and copyrights. I'm not up to date on all the current options in this space.

**Comment by oshoma** [comment]
@amirfz this issue can be
Closed now
