### ISSUE TITLE
provide verbose behavior as default

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/sherpa#93]
**current state**
when a question is asked, the assitant does not show any indication of working until an answer is ready to print. this causes confusion as to wether the system is working at all, but also is opaque in terms of how it has found the information it is printing which does not help with user trust

**ideal future state**

the assitant needs to print all the activities it is doing as they happen

**sample output**

User: {question}
Sherpa: I'm going to start looking up some information
<3 seconds wait>
Sherpa: calling {tool name} with query {query}
<3 seconds wait>
Sherpa: calling {tool name} with query {query}
<repeat until the final answer is ready>
Sherpa: {answer}

each of these should show as its own slack message as the execution is happening. I'm not sure if this requires some sort of a queue management or any changes in how the ReAct data is made available

**Comment by johnnykfeng** [comment]
@amirfz Okay, I get what you want now

After looking at the code closely, this will not be a simple solution, and may require big changes in the code.
Currently the output of Sherpa is processed in `task_agent.run()`, and it only returns after the entire process is finished, which is why it takes so long to get a response. One approach is to break down the entire process into several smaller methods e.g. `task_agent.decide_tool()`, `task_agent.execute_tool()`, etc. Then we can get return messages before the entire process is complete.

@20001LastOrder @YujingYang666777 what do you guys think about this idea?

**Comment by amirfz** [comment]
@johnnykfeng I think you are right! this will have to wait until we do the project restructuring

**Comment by johnnykfeng** [comment]
I have created a prototype solution, here's a demo: https://www.veed.io/view/ab4e3eed-a9f1-429e-9004-5f1d7ae36cbc?panel=share

Merge request will be coming soon

**Comment by amirfz** [comment]
@johnnykfeng how hard is it to change this to default behavior when we decide to do so?

**Comment by johnnykfeng** [comment]
> @johnnykfeng how hard is it to change this to default behavior when we decide to do so?

@amirfz in theory not hard at all, it's just removing the if condition `if contains_verbose(question):` in the code

**Comment by amirfz** [comment]
@johnnykfeng lets do that. it's ok that it doesn't always work, but at least we get better indications of when it fails

**Comment by johnnykfeng** [comment]
@amirfz You can close this issue
